### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by devendra-alt** [Aqurds/mv-bl#7]
## 🏅 Great Code Practice
✔️ DRY code approach being used
✔️ You are following SPA standards
✔️ Very optimistic javascript being written

😄 happy coding

**Comment by lily4178993** [comment]
All the work look great. You did a wonderful job.
Have a nice day

**Comment by Aqurds** [comment]
Thanks, both of you :+1: 
I appreciate the effort & time you put into the review.
